export const sectionData = [
  {
    name: "models",
    type: "models",
    buttonText: "Модели",
    title: "3D Модели (формат .glb)",
    id: "models-section",
    inputType: "file",
    accept: ".glb",
    required: true,
    submitText: "Загрузить модель"
  },
  {
    name: "categories",
    type: "categories",
    buttonText: "Категории",
    title: "Управление категориями",
    id: "categories-section",
    inputType: "text",
    accept: "",
    required: false,
    submitText: "",
  },
  {
    name: "videos",
    type: "video",
    buttonText: "Видео",
    title: "Видео (формат .mp4)",
    id: "video-section",
    inputType: "file",
    accept: ".mp4",
    required: true,
    submitText: "Загрузить видео",
  },
  {
    name: "sounds",
    type: "sound",
    buttonText: "Звуки",
    title: "Звуковые файлы (форматы .mp3 .wav)",
    id: "sounds-section",
    inputType: "file",
    accept: ".mp3,.wav",
    required: true,
    submitText: "Загрузить звук",
  },
  {
    name: "previews",
    type: "preview",
    buttonText: "Картинки",
    title: "Графические файлы (форматы .png .jpg .jpeg)",
    id: "previews-section",
    inputType: "file",
    accept: ".png,.jpg,.jpeg",
    required: true,
    submitText: "Загрузить картинку",
  },
  // {
  //   name: "descriptions",
  //   type: "description",
  //   buttonText: "Описания",
  //   title: "Описания (формат .txt)",
  //   id: "descriptions-section",
  //   inputType: "file",
  //   accept: ".txt",
  //   required: true,
  //   submitText: "Загрузить описание",
  // },
  {
    name: "patterns",
    type: "pattern",
    buttonText: "Паттерны",
    title: "Паттерны AR (формат .patt)",
    id: "patterns-section",
    inputType: "file",
    accept: ".patt",
    required: true,
    submitText: "Загрузить паттерн",
  },
]


