server.port=${SERVER_PORT:3062}

# Storage
storage.location=${STORAGE_LOCATION:../../storage}
patterns.location=${PATTERNS_LOCATION:../../storage/markers}
admin.password=${ADMIN_PASSWORD:ADMINPOLITEX01}

# File upload
spring.servlet.multipart.max-file-size=1000MB
spring.servlet.multipart.max-request-size=1000MB

server.compression.enabled=true
server.compression.mime-types=application/json,application/octet-stream,model/gltf-binary,text/plain
server.compression.min-response-size=1024

# PostgreSQL
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/miraclear}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:miraclear}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:miraclear123}
spring.jpa.hibernate.ddl-auto=update

# JPA
spring.jpa.show-sql=${JPA_SHOW_SQL:true}
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.hibernate.SQL=${LOG_LEVEL_HIBERNATE:DEBUG}

# JWT
jwt.secret=${JWT_SECRET:404E635266556A586E3272357538782F413F4428472B4B6250645367566B5970}
jwt.expiration=${JWT_EXPIRATION:86400000}